-- ============================================================================
-- La première liste d'applications recommandées.
--
-- Cinquante-quatre applications, choisies sur un seul critère : est-ce que ne
-- pas la connaître coûte de l'argent, du temps ou de la tranquillité ? Une
-- application de plus qui fait la même chose qu'une autre n'apporte rien ; une
-- carte de transport qu'on découvre le dernier jour, si.
--
-- Deux partis pris qui se voient dans les données :
--
--  1. **Les liens de magasin sont des recherches par nom**, pas des fiches.
--     Un identifiant App Store inventé mène à une application homonyme — au
--     mieux inutile, au pire malveillante. Une recherche « Saily » tombe sur
--     la bonne, et reste juste quand l'éditeur change d'identifiant.
--  2. **Aucune affirmation invérifiable.** On ne dit pas qu'une plateforme est
--     « indisponible dans tel pays » (c'est souvent faux, ou plus vrai) : on
--     dit que les catalogues diffèrent selon les pays et qu'il vaut mieux en
--     comparer deux. C'est ce qui reste exact dans deux ans.
--
-- La graine est rejouable : réappliquer la migration met à jour les textes
-- sans écraser une décision de modération.
-- ============================================================================

insert into public.travel_apps
  (id, name, category, tagline, why, caveat,
   ios_url, android_url, web_url, country_codes, destination_ids, status, priority)
values
  ('saily', 'Saily', 'connectivite',
   'Une eSIM data achetée avant de partir, activée à l''atterrissage.',
   'Le hors-forfait à l''étranger se facture encore au mégaoctet chez beaucoup d''opérateurs. Une eSIM s''achète en ligne, coûte quelques euros pour la semaine, et fonctionne dès l''atterrissage sans chercher une boutique ni un wifi.',
   'Demande un téléphone compatible eSIM et désimlocké. Gardez votre carte SIM physique active pour les appels et les codes reçus par SMS : l''eSIM ne sert qu''aux données.',
   'https://apps.apple.com/search?term=Saily', 'https://play.google.com/store/search?q=Saily&c=apps', 'https://saily.com',
   '{}', '{}', 'published', 90),
  ('airalo', 'Airalo', 'connectivite',
   'La même idée que Saily, avec des forfaits régionaux.',
   'Utile quand le voyage traverse plusieurs pays : un forfait « Europe » ou « Asie » évite d''en racheter un à chaque frontière. Comparez les deux, les prix varient beaucoup selon la destination.',
   null,
   'https://apps.apple.com/search?term=Airalo', 'https://play.google.com/store/search?q=Airalo&c=apps', 'https://www.airalo.com',
   '{}', '{}', 'published', 80),
  ('proton-vpn', 'Proton VPN', 'connectivite',
   'Un VPN gratuit qui ne se paie pas sur votre dos.',
   'Indispensable sur le wifi d''un aéroport ou d''un hôtel, et pour joindre vos services habituels depuis un pays qui les bloque. L''offre gratuite est sans publicité, sans limite de données et sans journalisation.',
   'Méfiez-vous des VPN gratuits financés par la publicité : beaucoup se rémunèrent en revendant l''historique de navigation, ce qui est exactement l''inverse de ce qu''on attend d''un VPN. Proton finance son offre gratuite par ses abonnés payants.',
   'https://apps.apple.com/search?term=Proton%20VPN', 'https://play.google.com/store/search?q=Proton%20VPN&c=apps', 'https://protonvpn.com',
   '{}', '{}', 'published', 85),
  ('organic-maps', 'Organic Maps', 'orientation',
   'Toute la carte du pays dans le téléphone, sans réseau ni compte.',
   'Se télécharge avant de partir et fonctionne en avion comme au fond d''une vallée. Aucun compte, aucune publicité, aucun pistage — les données viennent d''OpenStreetMap.',
   'Les avis et horaires y sont moins complets que sur Google Maps : c''est un outil d''orientation, pas de découverte.',
   'https://apps.apple.com/search?term=Organic%20Maps', 'https://play.google.com/store/search?q=Organic%20Maps&c=apps', 'https://organicmaps.app',
   '{}', '{}', 'published', 80),
  ('google-maps', 'Google Maps', 'orientation',
   'Les zones hors ligne, à préparer avant de partir.',
   'Peu de gens savent qu''on peut télécharger une zone entière et l''utiliser sans réseau, GPS compris. À faire depuis chez soi, sur le wifi, avant même de boucler la valise.',
   'Les transports en commun sont incomplets dans plusieurs pays, et l''application est peu utile en Chine ou en Corée du Sud où d''autres cartes font autorité.',
   'https://apps.apple.com/search?term=Google%20Maps', 'https://play.google.com/store/search?q=Google%20Maps&c=apps', 'https://maps.google.com',
   '{}', '{}', 'published', 75),
  ('google-translate', 'Google Traduction', 'langue',
   'Le pack hors ligne et l''appareil photo sur les menus.',
   'Téléchargez la langue avant de partir : la traduction fonctionne alors sans réseau. La photo d''un menu ou d''un panneau se traduit instantanément, ce qui change tout dans un pays dont on ne lit pas l''alphabet.',
   null,
   'https://apps.apple.com/search?term=Google%20Traduction', 'https://play.google.com/store/search?q=Google%20Traduction&c=apps', 'https://translate.google.com',
   '{}', '{}', 'published', 75),
  ('deepl', 'DeepL', 'langue',
   'Pour les phrases, quand la traduction doit être juste.',
   'Nettement meilleur que ses concurrents dès qu''il s''agit d''une phrase entière — écrire à un logeur, comprendre un courriel, expliquer un problème à une pharmacie.',
   'Moins de langues que Google Traduction, et pas de traduction par appareil photo.',
   'https://apps.apple.com/search?term=DeepL', 'https://play.google.com/store/search?q=DeepL&c=apps', 'https://www.deepl.com',
   '{}', '{}', 'published', 60),
  ('wise', 'Wise', 'argent',
   'Payer et retirer au vrai taux de change.',
   'La carte convertit au taux interbancaire avec une commission affichée, là où une banque classique ajoute 2 à 3 % sans le dire. Sur deux semaines de voyage, l''écart se compte en dizaines d''euros.',
   'Refusez toujours la conversion proposée par le distributeur ou le terminal (« payer en euros ? ») : c''est là que se cache le mauvais taux, quelle que soit la carte.',
   'https://apps.apple.com/search?term=Wise', 'https://play.google.com/store/search?q=Wise&c=apps', 'https://wise.com',
   '{}', '{}', 'published', 85),
  ('revolut', 'Revolut', 'argent',
   'Même principe, avec des sous-comptes par devise.',
   'Pratique pour mettre de côté le budget du voyage et voir ce qu''il en reste. Les retraits gratuits sont plafonnés selon la formule.',
   null,
   'https://apps.apple.com/search?term=Revolut', 'https://play.google.com/store/search?q=Revolut&c=apps', 'https://www.revolut.com',
   '{}', '{}', 'published', 70),
  ('xe-currency', 'XE Currency', 'argent',
   'Le taux du jour, même sans réseau.',
   'Garde le dernier taux connu en mémoire : on peut vérifier un prix au marché sans connexion, ce qui évite les conversions mentales approximatives.',
   null,
   'https://apps.apple.com/search?term=XE%20Currency', 'https://play.google.com/store/search?q=XE%20Currency&c=apps', 'https://www.xe.com',
   '{}', '{}', 'published', 55),
  ('getyourguide', 'GetYourGuide', 'activites',
   'Billets et visites, souvent annulables.',
   'Évite les files d''attente sur les sites très fréquentés, et beaucoup de réservations s''annulent gratuitement jusqu''à 24 h avant — utile quand la météo décide à votre place.',
   'Comparez avec le tarif du guichet officiel : la commodité se paie parfois cher sur les entrées simples.',
   'https://apps.apple.com/search?term=GetYourGuide', 'https://play.google.com/store/search?q=GetYourGuide&c=apps', 'https://www.getyourguide.com',
   '{}', '{}', 'published', 75),
  ('rome2rio', 'Rome2Rio', 'transport_longue',
   'Comment aller de A à B, par tous les moyens.',
   'Donne d''un coup les options train, bus, avion, ferry et voiture avec durées et ordres de prix, y compris pour des trajets que personne ne pense à comparer.',
   'Les prix sont indicatifs : la réservation se fait ensuite chez l''opérateur.',
   'https://apps.apple.com/search?term=Rome2Rio', 'https://play.google.com/store/search?q=Rome2Rio&c=apps', 'https://www.rome2rio.com',
   '{}', '{}', 'published', 75),
  ('skyscanner', 'Skyscanner', 'transport_longue',
   'Chercher « partout », et laisser le prix décider.',
   'La recherche « Partout » avec des dates souples est la meilleure façon de trouver une destination bon marché quand le groupe n''a pas d''idée fixe.',
   null,
   'https://apps.apple.com/search?term=Skyscanner', 'https://play.google.com/store/search?q=Skyscanner&c=apps', 'https://www.skyscanner.fr',
   '{}', '{}', 'published', 70),
  ('omio', 'Omio', 'transport_longue',
   'Trains et bus européens, tous opérateurs.',
   'Compare en une recherche des compagnies qui ne se comparent nulle part ailleurs, ce qui évite d''ouvrir six sites nationaux.',
   null,
   'https://apps.apple.com/search?term=Omio', 'https://play.google.com/store/search?q=Omio&c=apps', 'https://www.omio.fr',
   array['FR','DE','IT','ES','PT','NL','BE','AT','CH','CZ','PL','HU','GB','IE','DK','SE','NO','GR','HR','SI','SK','RO','BG']::text[], '{}', 'published', 65),
  ('flixbus', 'FlixBus', 'transport_longue',
   'Le bus longue distance à prix cassé.',
   'Souvent trois à cinq fois moins cher que le train pour les mêmes villes, au prix de quelques heures de plus. Sur un budget serré, c''est ce qui rend le voyage possible.',
   null,
   'https://apps.apple.com/search?term=FlixBus', 'https://play.google.com/store/search?q=FlixBus&c=apps', 'https://www.flixbus.fr',
   array['FR','DE','IT','ES','PT','NL','BE','AT','CH','CZ','PL','HU','HR','SI','DK','SE','RO','BG','US']::text[], '{}', 'published', 60),
  ('12go', '12Go', 'transport_longue',
   'Bus, trains et ferries en Asie, réservés à l''avance.',
   'En Asie du Sud-Est, les liaisons se réservent souvent sur place et en liquide. Le faire à l''avance évite d''arriver à une gare routière déjà pleine.',
   null,
   'https://apps.apple.com/search?term=12Go', 'https://play.google.com/store/search?q=12Go&c=apps', 'https://12go.asia',
   array['TH','VN','KH','LA','MY','SG','ID','PH','IN','LK','JP','KR','TW']::text[], '{}', 'published', 65),
  ('too-good-to-go', 'Too Good To Go', 'nourriture',
   'Les invendus du jour, au tiers du prix.',
   'Boulangeries, épiceries et restaurants y bradent ce qui ne passera pas la nuit. Un vrai repas pour trois ou quatre euros, dans des villes où c''est souvent le poste qui dérape.',
   'Le panier est une surprise et se récupère dans un créneau précis : à réserver le matin pour le soir même.',
   'https://apps.apple.com/search?term=Too%20Good%20To%20Go', 'https://play.google.com/store/search?q=Too%20Good%20To%20Go&c=apps', 'https://www.toogoodtogo.com',
   array['FR','ES','IT','PT','DE','NL','BE','AT','CH','DK','SE','NO','PL','IE','GB','US','CA']::text[], '{}', 'published', 70),
  ('bolt', 'Bolt', 'transport_local',
   'Course en voiture, souvent moins chère qu''Uber.',
   'Présent dans une quarantaine de pays, avec un prix annoncé avant de monter — ce qui règle la question du prix négocié à l''arrivée. Propose aussi trottinettes et vélos dans beaucoup de villes.',
   null,
   'https://apps.apple.com/search?term=Bolt', 'https://play.google.com/store/search?q=Bolt&c=apps', 'https://bolt.eu',
   array['EE','LV','LT','PL','CZ','SK','RO','BG','HR','RS','ME','MK','AL','XK','BA','PT','ES','FR','DE','SE','NO','FI','GB','IE','MT','CY','GR','TR','GE','AZ','ZA','KE','NG','GH','TN','MA']::text[], '{}', 'published', 85),
  ('uber', 'Uber', 'transport_local',
   'La valeur sûre là où elle existe.',
   'Le prix est fixé d''avance et le trajet enregistré, ce qui compte quand on ne parle pas la langue et qu''on ne connaît pas le chemin.',
   'Absent ou marginal dans plusieurs pays — vérifiez avant de compter dessus, et gardez une application locale en secours.',
   'https://apps.apple.com/search?term=Uber', 'https://play.google.com/store/search?q=Uber&c=apps', 'https://www.uber.com',
   '{}', '{}', 'published', 75),
  ('citymapper', 'Citymapper', 'transport_local',
   'Les transports en commun expliqués comme à un local.',
   'Donne la sortie de métro à prendre, la voiture où monter et le prix du trajet, dans une centaine de grandes villes.',
   'Ne couvre que les grandes agglomérations : ailleurs, Moovit prend le relais.',
   'https://apps.apple.com/search?term=Citymapper', 'https://play.google.com/store/search?q=Citymapper&c=apps', 'https://citymapper.com',
   '{}', '{}', 'published', 70),
  ('moovit', 'Moovit', 'transport_local',
   'Les transports en commun, y compris là où personne ne les cartographie.',
   'Couvre des milliers de villes moyennes que les grandes applications ignorent, avec des horaires souvent tenus à jour par les usagers eux-mêmes.',
   null,
   'https://apps.apple.com/search?term=Moovit', 'https://play.google.com/store/search?q=Moovit&c=apps', 'https://moovitapp.com',
   '{}', '{}', 'published', 65),
  ('indrive', 'inDrive', 'transport_local',
   'On propose son prix, le chauffeur accepte ou non.',
   'Le marchandage, mais dans l''application et sans parler la langue. Souvent le moins cher là où il est présent, notamment en Amérique latine, en Asie centrale et en Afrique.',
   null,
   'https://apps.apple.com/search?term=inDrive', 'https://play.google.com/store/search?q=inDrive&c=apps', 'https://indrive.com',
   array['KZ','KG','UZ','GE','AZ','AM','MX','CO','PE','BR','AR','CL','EC','GT','EG','MA','ZA','KE','TZ','IN','ID','TH','VN','PH']::text[], '{}', 'published', 60),
  ('agoda', 'Agoda', 'hebergement',
   'Souvent le plus fourni en Asie et en Turquie.',
   'Les plateformes n''ont pas le même catalogue selon les pays : un hôtel introuvable ailleurs y apparaît, et parfois moins cher.',
   'La disponibilité et les prix des plateformes de réservation varient beaucoup d''un pays à l''autre. Installez-en deux et comparez plutôt que de vous fier à une seule.',
   'https://apps.apple.com/search?term=Agoda', 'https://play.google.com/store/search?q=Agoda&c=apps', 'https://www.agoda.com',
   '{}', '{}', 'published', 75),
  ('booking', 'Booking.com', 'hebergement',
   'Le catalogue le plus large en Europe.',
   'L''annulation gratuite y est fréquente, ce qui permet de bloquer une chambre pendant que le groupe se décide.',
   null,
   'https://apps.apple.com/search?term=Booking.com', 'https://play.google.com/store/search?q=Booking.com&c=apps', 'https://www.booking.com',
   '{}', '{}', 'published', 75),
  ('hostelworld', 'Hostelworld', 'hebergement',
   'Les auberges, quand on part à plusieurs et sans budget.',
   'Beaucoup d''auberges proposent des chambres privées pour quatre ou six : le prix d''un dortoir avec l''intimité d''un hôtel. C''est souvent la meilleure option pour un groupe d''amis.',
   null,
   'https://apps.apple.com/search?term=Hostelworld', 'https://play.google.com/store/search?q=Hostelworld&c=apps', 'https://www.hostelworld.com',
   '{}', '{}', 'published', 65),
  ('airbnb', 'Airbnb', 'hebergement',
   'Un logement entier, pour cuisiner et se poser.',
   'Sur une semaine à plusieurs, une cuisine fait souvent plus d''économies que la différence de prix avec l''hôtel.',
   'Vérifiez le total avec les frais de ménage et de service : ils changent complètement le classement des annonces.',
   'https://apps.apple.com/search?term=Airbnb', 'https://play.google.com/store/search?q=Airbnb&c=apps', 'https://www.airbnb.fr',
   '{}', '{}', 'published', 65),
  ('ariane', 'Ariane', 'securite',
   'Signaler son voyage au Quai d''Orsay, gratuitement.',
   'En cas de crise dans le pays, le consulat sait que vous y êtes et peut vous joindre. Cinq minutes avant de partir, et rien à faire ensuite.',
   'Réservé aux ressortissants français. D''autres pays proposent un service équivalent.',
   'https://apps.apple.com/search?term=Ariane', 'https://play.google.com/store/search?q=Ariane&c=apps', 'https://pastel.diplomatie.gouv.fr/fildariane',
   '{}', '{}', 'published', 55),
  ('bitaksi', 'BiTaksi', 'transport_local',
   'Le taxi stambouliote, sans négociation.',
   'Appelle un taxi officiel avec le compteur et le trajet enregistré. Règle d''un coup le problème du prix annoncé à la tête du client, qui est le grief numéro un des visiteurs à Istanbul.',
   null,
   'https://apps.apple.com/search?term=BiTaksi', 'https://play.google.com/store/search?q=BiTaksi&c=apps', 'https://bitaksi.com',
   array['TR']::text[], '{}', 'published', 90),
  ('istanbulkart', 'İstanbulkart', 'transport_local',
   'La carte qui ouvre métro, tram, bus, funiculaire et ferry.',
   'Sans elle, chaque trajet coûte nettement plus cher et se paie à un guichet. La carte s''achète dans n''importe quelle station pour quelques livres et se recharge à l''application ou aux bornes. Une seule carte peut payer pour plusieurs personnes.',
   'Prenez-la dès l''aéroport : le trajet vers le centre est déjà rentabilisé. Les ferries du Bosphore fonctionnent avec, et coûtent le prix d''un ticket de métro pour la plus belle traversée de la ville.',
   'https://apps.apple.com/search?term=%C4%B0stanbulkart', 'https://play.google.com/store/search?q=%C4%B0stanbulkart&c=apps', 'https://www.istanbulkart.istanbul',
   array['TR']::text[], array['istanbul']::text[], 'published', 95),
  ('obilet', 'Obilet', 'transport_longue',
   'Bus entre les villes turques, et vols intérieurs.',
   'Le réseau de bus turc est excellent et bon marché, mais se réserve en turc chez chaque compagnie. Obilet les rassemble et affiche les prix en une recherche.',
   null,
   'https://apps.apple.com/search?term=Obilet', 'https://play.google.com/store/search?q=Obilet&c=apps', 'https://www.obilet.com',
   array['TR']::text[], '{}', 'published', 80),
  ('yemeksepeti', 'Yemeksepeti', 'nourriture',
   'La livraison de repas historique en Turquie.',
   'Couvre des restaurants que les applications internationales n''ont pas, jusque dans les villes moyennes.',
   null,
   'https://apps.apple.com/search?term=Yemeksepeti', 'https://play.google.com/store/search?q=Yemeksepeti&c=apps', 'https://www.yemeksepeti.com',
   array['TR']::text[], '{}', 'published', 70),
  ('trendyol-go', 'Trendyol Go', 'nourriture',
   'L''autre livraison, souvent moins chère.',
   'Les promotions diffèrent d''une application à l''autre : avoir les deux fait gagner sur presque chaque commande.',
   null,
   'https://apps.apple.com/search?term=Trendyol%20Go', 'https://play.google.com/store/search?q=Trendyol%20Go&c=apps', 'https://www.trendyolgo.com',
   array['TR']::text[], '{}', 'published', 65),
  ('getir', 'Getir', 'nourriture',
   'Les courses livrées en quelques minutes.',
   'Eau, petit-déjeuner, dépannage du soir. Pratique en location quand les épiceries ferment tôt.',
   null,
   'https://apps.apple.com/search?term=Getir', 'https://play.google.com/store/search?q=Getir&c=apps', 'https://getir.com',
   array['TR']::text[], '{}', 'published', 55),
  ('grab', 'Grab', 'transport_local',
   'Le tout-en-un de l''Asie du Sud-Est.',
   'Voiture, moto-taxi, livraison de repas et paiement dans une seule application. La moto-taxi coûte une fraction de la voiture et traverse les embouteillages de Bangkok ou Jakarta.',
   null,
   'https://apps.apple.com/search?term=Grab', 'https://play.google.com/store/search?q=Grab&c=apps', 'https://www.grab.com',
   array['TH','VN','ID','MY','SG','PH','KH','MM']::text[], '{}', 'published', 90),
  ('gojek', 'Gojek', 'transport_local',
   'L''équivalent indonésien, souvent moins cher.',
   'Les deux coexistent en Indonésie et se concurrencent : comparer les deux prix prend dix secondes.',
   null,
   'https://apps.apple.com/search?term=Gojek', 'https://play.google.com/store/search?q=Gojek&c=apps', 'https://www.gojek.com',
   array['ID','SG','VN']::text[], '{}', 'published', 75),
  ('careem', 'Careem', 'transport_local',
   'La référence au Moyen-Orient et en Afrique du Nord.',
   'Racheté par Uber mais resté distinct, avec une meilleure couverture locale et le paiement en espèces accepté.',
   null,
   'https://apps.apple.com/search?term=Careem', 'https://play.google.com/store/search?q=Careem&c=apps', 'https://www.careem.com',
   array['AE','SA','EG','JO','QA','OM','BH','KW','MA','PK']::text[], '{}', 'published', 80),
  ('didi', 'DiDi', 'transport_local',
   'Le VTC dominant en Chine et en Amérique latine.',
   'En Chine, l''application propose une interface en anglais et gère la barrière de la langue avec le chauffeur.',
   null,
   'https://apps.apple.com/search?term=DiDi', 'https://play.google.com/store/search?q=DiDi&c=apps', 'https://web.didiglobal.com',
   array['CN','MX','BR','AR','CL','CO','PE','AU','JP','NZ','EG']::text[], '{}', 'published', 75),
  ('free-now', 'FREE NOW', 'transport_local',
   'Taxis officiels et VTC dans une même application.',
   'Utile là où le taxi de rue reste roi : on garde le compteur officiel sans avoir à héler dans la rue.',
   null,
   'https://apps.apple.com/search?term=FREE%20NOW', 'https://play.google.com/store/search?q=FREE%20NOW&c=apps', 'https://www.free-now.com',
   array['DE','AT','ES','IT','IE','GB','PL','GR']::text[], '{}', 'published', 60),
  ('99', '99', 'transport_local',
   'Le VTC brésilien.',
   'Souvent moins cher qu''Uber au Brésil, et accepte les espèces.',
   null,
   'https://apps.apple.com/search?term=99', 'https://play.google.com/store/search?q=99&c=apps', 'https://99app.com',
   array['BR']::text[], '{}', 'published', 60),
  ('kakao-t', 'Kakao T', 'transport_local',
   'Le taxi en Corée du Sud.',
   'Les VTC internationaux n''y fonctionnent presque pas : c''est l''application qu''utilisent les Coréens.',
   null,
   'https://apps.apple.com/search?term=Kakao%20T', 'https://play.google.com/store/search?q=Kakao%20T&c=apps', 'https://www.kakaocorp.com',
   array['KR']::text[], '{}', 'published', 75),
  ('naver-map', 'Naver Map', 'orientation',
   'La carte qui marche vraiment en Corée.',
   'Google Maps y est bridé par la loi et donne des itinéraires piétons incomplets. Naver Map, avec son interface en anglais, est ce qu''utilisent les locaux.',
   null,
   'https://apps.apple.com/search?term=Naver%20Map', 'https://play.google.com/store/search?q=Naver%20Map&c=apps', 'https://map.naver.com',
   array['KR']::text[], '{}', 'published', 85),
  ('navitime', 'Japan Travel by NAVITIME', 'transport_local',
   'Les trains japonais expliqués en anglais.',
   'Donne le quai, la correspondance et si le train est couvert par le Japan Rail Pass — ce que les autres applications ne disent pas.',
   null,
   'https://apps.apple.com/search?term=Japan%20Travel%20by%20NAVITIME', 'https://play.google.com/store/search?q=Japan%20Travel%20by%20NAVITIME&c=apps', 'https://japantravel.navitime.com',
   array['JP']::text[], '{}', 'published', 85),
  ('suica', 'Suica', 'transport_local',
   'La carte de transport, directement dans le téléphone.',
   'S''ajoute au portefeuille du téléphone et se recharge par carte bancaire : plus de distributeur à trouver, et elle paie aussi dans les supérettes et les distributeurs de boissons.',
   'L''ajout depuis un iPhone est direct ; sur Android, il faut un téléphone acheté au Japon. À défaut, la carte physique s''achète en gare.',
   'https://apps.apple.com/search?term=Suica', 'https://play.google.com/store/search?q=Suica&c=apps', 'https://www.jreast.co.jp',
   array['JP']::text[], '{}', 'published', 85),
  ('alipay', 'Alipay', 'argent',
   'Payer en Chine quand on n''a pas de compte chinois.',
   'L''espèce a presque disparu et les cartes étrangères passent mal. Alipay accepte désormais les cartes internationales pour les visiteurs : sans ça, payer un taxi ou un thé devient un problème quotidien.',
   'À configurer avant le départ, avec le passeport : la vérification prend parfois un jour.',
   'https://apps.apple.com/search?term=Alipay', 'https://play.google.com/store/search?q=Alipay&c=apps', 'https://www.alipay.com',
   array['CN']::text[], '{}', 'published', 95),
  ('irctc', 'IRCTC Rail Connect', 'transport_longue',
   'Les trains indiens, réservés à l''avance.',
   'Le train longue distance se remplit des semaines à l''avance en Inde. Réserver depuis l''application évite les files et les intermédiaires qui prennent une commission.',
   'L''inscription demande un numéro indien ou une vérification qui peut prendre du temps : à préparer avant de partir.',
   'https://apps.apple.com/search?term=IRCTC%20Rail%20Connect', 'https://play.google.com/store/search?q=IRCTC%20Rail%20Connect&c=apps', 'https://www.irctc.co.in',
   array['IN']::text[], '{}', 'published', 80),
  ('redbus', 'redBus', 'transport_longue',
   'Les bus, en Inde et au-delà.',
   'Rassemble des centaines de compagnies privées et affiche les avis sur l''état des bus, ce qui compte sur douze heures de trajet.',
   null,
   'https://apps.apple.com/search?term=redBus', 'https://play.google.com/store/search?q=redBus&c=apps', 'https://www.redbus.in',
   array['IN','ID','MY','SG','PE','CO']::text[], '{}', 'published', 65),
  ('glovo', 'Glovo', 'nourriture',
   'Livraison de repas et de courses en Europe du Sud et au Maghreb.',
   'Couvre aussi les pharmacies et les supermarchés, ce qui dépanne un dimanche.',
   null,
   'https://apps.apple.com/search?term=Glovo', 'https://play.google.com/store/search?q=Glovo&c=apps', 'https://glovoapp.com',
   array['ES','IT','PT','PL','RO','BG','HR','RS','UA','GE','AM','MA','CI','KE']::text[], '{}', 'published', 65),
  ('wolt', 'Wolt', 'nourriture',
   'La livraison dans les pays nordiques, l''Europe centrale et le Caucase.',
   'Souvent la seule application de livraison qui fonctionne à Tbilissi, Belgrade ou Helsinki.',
   null,
   'https://apps.apple.com/search?term=Wolt', 'https://play.google.com/store/search?q=Wolt&c=apps', 'https://wolt.com',
   array['FI','SE','NO','DK','DE','PL','CZ','HU','SK','GR','CY','RS','HR','GE','IL','KZ']::text[], '{}', 'published', 65),
  ('talabat', 'Talabat', 'nourriture',
   'La livraison au Moyen-Orient.',
   'Repas, courses et pharmacie, avec des restaurants qui n''apparaissent nulle part ailleurs.',
   null,
   'https://apps.apple.com/search?term=Talabat', 'https://play.google.com/store/search?q=Talabat&c=apps', 'https://www.talabat.com',
   array['AE','SA','KW','QA','BH','OM','EG','JO']::text[], '{}', 'published', 60),
  ('ifood', 'iFood', 'nourriture',
   'La livraison brésilienne.',
   'Domine le marché : c''est là que sont les restaurants et les promotions.',
   null,
   'https://apps.apple.com/search?term=iFood', 'https://play.google.com/store/search?q=iFood&c=apps', 'https://www.ifood.com.br',
   array['BR']::text[], '{}', 'published', 60),
  ('rappi', 'Rappi', 'nourriture',
   'Livraison et courses en Amérique latine.',
   'Livre aussi de l''argent liquide dans certains pays, ce qui évite de chercher un distributeur le soir.',
   null,
   'https://apps.apple.com/search?term=Rappi', 'https://play.google.com/store/search?q=Rappi&c=apps', 'https://www.rappi.com',
   array['CO','MX','BR','AR','CL','PE','UY','CR','EC']::text[], '{}', 'published', 60),
  ('swiggy', 'Swiggy', 'nourriture',
   'La livraison en Inde.',
   'Avec Zomato, se partage le pays : les restaurants diffèrent, comparer vaut le coup.',
   null,
   'https://apps.apple.com/search?term=Swiggy', 'https://play.google.com/store/search?q=Swiggy&c=apps', 'https://www.swiggy.com',
   array['IN']::text[], '{}', 'published', 55),
  ('trainline', 'Trainline', 'transport_longue',
   'Les trains britanniques et européens.',
   'Au Royaume-Uni, le prix d''un même trajet varie du simple au triple selon l''heure d''achat : l''application montre le tarif le moins cher de la journée.',
   null,
   'https://apps.apple.com/search?term=Trainline', 'https://play.google.com/store/search?q=Trainline&c=apps', 'https://www.thetrainline.com',
   array['GB','FR','IT','ES','DE','NL','BE','AT','CH','IE']::text[], '{}', 'published', 65),
  ('transit', 'Transit', 'transport_local',
   'Les transports en Amérique du Nord.',
   'Bien plus fiable que les applications officielles des réseaux, avec la position réelle des bus.',
   null,
   'https://apps.apple.com/search?term=Transit', 'https://play.google.com/store/search?q=Transit&c=apps', 'https://transitapp.com',
   array['US','CA']::text[], '{}', 'published', 60)
on conflict (id) do update set
  name            = excluded.name,
  category        = excluded.category,
  tagline         = excluded.tagline,
  why             = excluded.why,
  caveat          = excluded.caveat,
  ios_url         = excluded.ios_url,
  android_url     = excluded.android_url,
  web_url         = excluded.web_url,
  country_codes   = excluded.country_codes,
  destination_ids = excluded.destination_ids,
  priority        = excluded.priority,
  -- On ne repasse pas en 'published' une fiche qu'un administrateur aurait
  -- retirée : la modération humaine prime sur la graine.
  status          = case when public.travel_apps.status = 'rejected'
                         then 'rejected' else excluded.status end,
  updated_at      = now();
