-- ============================================================================
-- Vingt-huit applications de plus, là où le catalogue laissait un vide.
--
-- La première vague couvrait bien l'Europe de l'Ouest, l'Asie du Sud-Est et la
-- Turquie, et laissait cinquante-huit pays du catalogue sans une seule
-- recommandation locale. Un voyageur qui part à Alger, à Katmandou ou à
-- Hong Kong n'y trouvait que des conseils mondiaux, c'est-à-dire ceux qu'il
-- connaissait déjà.
--
-- Le tri est le même qu'ailleurs dans le projet : on ajoute une fiche quand ne
-- pas la connaître coûte quelque chose. D'où la présence des trains nationaux
-- européens — le prix d'un Frecciarossa et d'un Regionale sur le même trajet
-- va du simple au triple — et l'absence des dizaines d'îles où la vraie
-- réponse est « rien de particulier », qu'il vaut mieux dire en ne disant rien
-- que de meubler avec une application inventée.
-- ============================================================================

insert into public.travel_apps
  (id, name, category, tagline, why, caveat,
   ios_url, android_url, web_url, country_codes, destination_ids, status, priority)
values
  ('sncf-connect', 'SNCF Connect', 'transport_longue',
   'Les trains français, et les billets à petit prix.',
   'Les billets ouvrent à la vente plusieurs mois à l''avance et les tarifs les plus bas partent en premier. L''application montre aussi les cartes de réduction, rentables dès deux allers-retours.',
   null,
   'https://apps.apple.com/search?term=SNCF%20Connect', 'https://play.google.com/store/search?q=SNCF%20Connect&c=apps', 'https://www.sncf-connect.com',
   array['FR']::text[], '{}', 'published', 75),
  ('renfe', 'Renfe', 'transport_longue',
   'Les trains espagnols, AVE compris.',
   'L''Espagne a le deuxième réseau à grande vitesse du monde et des tarifs réellement bas quand on réserve tôt. Depuis l''ouverture à la concurrence, comparez aussi Ouigo et Iryo sur les mêmes lignes.',
   null,
   'https://apps.apple.com/search?term=Renfe', 'https://play.google.com/store/search?q=Renfe&c=apps', 'https://www.renfe.com',
   array['ES']::text[], '{}', 'published', 70),
  ('trenitalia', 'Trenitalia', 'transport_longue',
   'Les trains italiens, et le bon type de train.',
   'La différence entre un Frecciarossa et un Regionale, c''est deux heures et le triple du prix sur le même trajet. L''application le dit, un moteur de recherche étranger rarement.',
   'Le billet Regionale doit être composté ou validé dans l''application avant de monter : le contrôle est strict et l''amende immédiate.',
   'https://apps.apple.com/search?term=Trenitalia', 'https://play.google.com/store/search?q=Trenitalia&c=apps', 'https://www.trenitalia.com',
   array['IT']::text[], '{}', 'published', 70),
  ('db-navigator', 'DB Navigator', 'transport_longue',
   'Les horaires de presque toute l''Europe, dans une seule application.',
   'La base horaire allemande couvre les trains de nombreux pays voisins, y compris les correspondances régionales que les comparateurs ignorent. C''est l''outil pour savoir si un trajet existe, avant même de savoir où l''acheter.',
   null,
   'https://apps.apple.com/search?term=DB%20Navigator', 'https://play.google.com/store/search?q=DB%20Navigator&c=apps', 'https://www.bahn.de',
   array['DE','AT','CH','NL','BE','DK','PL','CZ','LU']::text[], '{}', 'published', 75),
  ('rail-planner', 'Rail Planner', 'transport_longue',
   'Tous les horaires ferroviaires européens, hors ligne.',
   'Conçue pour les pass Interrail mais utilisable sans en avoir un : elle télécharge les horaires de trente pays et fonctionne dans un train sans réseau, ce qu''aucun site ne fait.',
   null,
   'https://apps.apple.com/search?term=Rail%20Planner', 'https://play.google.com/store/search?q=Rail%20Planner&c=apps', 'https://www.interrail.eu',
   array['FR','DE','IT','ES','PT','NL','BE','AT','CH','CZ','PL','HU','GR','HR','SI','SK','RO','BG','DK','SE','NO','FI','IE','GB','RS','ME','MK','TR','LU']::text[], '{}', 'published', 70),
  ('ns', 'NS', 'transport_longue',
   'Les trains néerlandais, et le supplément à ne pas oublier.',
   'Le réseau est dense et ponctuel, mais les trains rapides demandent un supplément que l''application ajoute automatiquement — payé après coup, il coûte plus cher.',
   null,
   'https://apps.apple.com/search?term=NS', 'https://play.google.com/store/search?q=NS&c=apps', 'https://www.ns.nl',
   array['NL']::text[], '{}', 'published', 55),
  ('sbb', 'SBB Mobile', 'transport_longue',
   'Les trains, bus, bateaux et téléphériques suisses.',
   'Tout le pays est dans un seul horaire, correspondances de trois minutes comprises, et elles sont tenues. L''application vend aussi les billets dégriffés, seule façon de rendre la Suisse abordable en train.',
   null,
   'https://apps.apple.com/search?term=SBB%20Mobile', 'https://play.google.com/store/search?q=SBB%20Mobile&c=apps', 'https://www.sbb.ch',
   array['CH']::text[], '{}', 'published', 70),
  ('oebb', 'ÖBB', 'transport_longue',
   'Les trains autrichiens et les trains de nuit.',
   'L''Autriche a relancé les trains de nuit vers une dizaine de capitales européennes : une nuit d''hôtel économisée et un vol en moins, réservables ici.',
   null,
   'https://apps.apple.com/search?term=%C3%96BB', 'https://play.google.com/store/search?q=%C3%96BB&c=apps', 'https://www.oebb.at',
   array['AT']::text[], '{}', 'published', 65),
  ('mobiliteit', 'Mobiliteit.lu', 'transport_local',
   'Les transports luxembourgeois, gratuits dans tout le pays.',
   'Le Luxembourg a rendu bus, trams et trains gratuits pour tout le monde, résidents comme visiteurs. Il n''y a rien à acheter : l''application sert uniquement à savoir quoi prendre et quand.',
   'La gratuité s''arrête à la première classe et aux trajets qui sortent du pays.',
   'https://apps.apple.com/search?term=Mobiliteit.lu', 'https://play.google.com/store/search?q=Mobiliteit.lu&c=apps', 'https://www.mobiliteit.lu',
   array['LU']::text[], '{}', 'published', 80),
  ('blablacar', 'BlaBlaCar', 'transport_longue',
   'Le covoiturage longue distance, souvent imbattable.',
   'Sur les trajets que le train dessert mal ou fait payer cher, une place en voiture coûte le prix du carburant partagé. Le réseau est dense en France, en Espagne, en Pologne, au Brésil et en Turquie.',
   'Le conducteur choisit son point de rendez-vous : vérifiez qu''il est accessible en transport avant de réserver, surtout à l''arrivée de nuit.',
   'https://apps.apple.com/search?term=BlaBlaCar', 'https://play.google.com/store/search?q=BlaBlaCar&c=apps', 'https://www.blablacar.fr',
   array['FR','ES','PT','IT','DE','PL','UA','TR','BR','MX','RO','HU','CZ','SK','RS','BE','NL','IN','MA']::text[], '{}', 'published', 75),
  ('cabify', 'Cabify', 'transport_local',
   'Le concurrent ibérique et latino-américain d''Uber.',
   'Prix fixé à la réservation, voitures souvent plus confortables, et présent dans des villes où Uber ne l''est pas ou plus.',
   null,
   'https://apps.apple.com/search?term=Cabify', 'https://play.google.com/store/search?q=Cabify&c=apps', 'https://cabify.com',
   array['ES','PT','CL','MX','CO','PE','AR','UY','DO']::text[], '{}', 'published', 70),
  ('yango', 'Yango', 'transport_local',
   'Le VTC qui couvre l''Afrique de l''Ouest et le Sahel.',
   'Dans plusieurs capitales africaines, c''est la seule application de course avec un prix affiché d''avance, là où le taxi de rue se négocie à chaque trajet.',
   'La couverture change vite d''un pays à l''autre : vérifiez que la ville est desservie avant de compter dessus, et gardez de quoi payer un taxi en liquide.',
   'https://apps.apple.com/search?term=Yango', 'https://play.google.com/store/search?q=Yango&c=apps', 'https://yango.com',
   array['SN','CI','GH','ZM','ET','MZ','MA','TN','PK','KZ','AE','BO','PE','CM']::text[], '{}', 'published', 75),
  ('yassir', 'Yassir', 'transport_local',
   'Le VTC et la livraison en Algérie.',
   'Les applications internationales n''y opèrent pas. Yassir est l''application qu''utilisent les Algérois pour se déplacer, avec un prix annoncé avant la course.',
   null,
   'https://apps.apple.com/search?term=Yassir', 'https://play.google.com/store/search?q=Yassir&c=apps', 'https://yassir.com',
   array['DZ','TN','MA','SN']::text[], '{}', 'published', 85),
  ('bykea', 'Bykea', 'transport_local',
   'La moto-taxi au Pakistan.',
   'Coûte une fraction d''une voiture et traverse des embouteillages où rien d''autre n''avance. Sert aussi à faire livrer et à envoyer de l''argent.',
   null,
   'https://apps.apple.com/search?term=Bykea', 'https://play.google.com/store/search?q=Bykea&c=apps', 'https://bykea.com',
   array['PK']::text[], '{}', 'published', 75),
  ('pathao', 'Pathao', 'transport_local',
   'Moto-taxi et livraison au Népal et au Bangladesh.',
   'À Katmandou, la moto est le seul moyen rapide de traverser la ville, et l''application évite d''avoir à négocier chaque course en népalais.',
   null,
   'https://apps.apple.com/search?term=Pathao', 'https://play.google.com/store/search?q=Pathao&c=apps', 'https://pathao.com',
   array['NP','BD']::text[], '{}', 'published', 75),
  ('marti', 'Martı', 'transport_local',
   'Trottinettes, scooters et taxis en Turquie.',
   'Le module taxi appelle un taxi officiel avec le compteur, comme BiTaksi : avoir les deux double les chances d''en trouver un aux heures de pointe.',
   null,
   'https://apps.apple.com/search?term=Mart%C4%B1', 'https://play.google.com/store/search?q=Mart%C4%B1&c=apps', 'https://www.marti.tech',
   array['TR']::text[], '{}', 'published', 65),
  ('lyft', 'Lyft', 'transport_local',
   'L''autre VTC nord-américain.',
   'Les prix des deux applications divergent fortement selon l''heure et le quartier ; comparer avant de commander prend quinze secondes et coûte souvent plusieurs dollars de moins.',
   null,
   'https://apps.apple.com/search?term=Lyft', 'https://play.google.com/store/search?q=Lyft&c=apps', 'https://www.lyft.com',
   array['US','CA']::text[], '{}', 'published', 60),
  ('amap', 'Amap', 'orientation',
   'La carte qui fonctionne en Chine.',
   'Google Maps n''y est pas utilisable et les cartes étrangères y sont décalées par la loi. Amap propose une interface en anglais et donne les itinéraires en transport que rien d''autre ne donne sur place.',
   null,
   'https://apps.apple.com/search?term=Amap', 'https://play.google.com/store/search?q=Amap&c=apps', 'https://mobile.amap.com',
   array['CN']::text[], '{}', 'published', 90),
  ('wechat', 'WeChat', 'argent',
   'Le passe-partout chinois : payer, appeler un taxi, réserver.',
   'Une grande partie des commerces, des musées et des files d''attente passe par un mini-programme WeChat. Sans lui, on se retrouve à ne pas pouvoir payer là où tout le monde paie en deux secondes.',
   'L''ajout d''une carte bancaire étrangère fonctionne mais demande une vérification d''identité : à faire avant le départ, pas à la caisse d''un restaurant.',
   'https://apps.apple.com/search?term=WeChat', 'https://play.google.com/store/search?q=WeChat&c=apps', 'https://www.wechat.com',
   array['CN']::text[], '{}', 'published', 90),
  ('trip-com', 'Trip.com', 'transport_longue',
   'Les trains chinois et les vols asiatiques, réservables de l''étranger.',
   'Le site officiel des chemins de fer chinois est difficilement utilisable sans compte local. Trip.com vend les mêmes billets avec passeport, en anglais, et les trains à grande vitesse se remplissent des semaines à l''avance.',
   null,
   'https://apps.apple.com/search?term=Trip.com', 'https://play.google.com/store/search?q=Trip.com&c=apps', 'https://www.trip.com',
   array['CN','HK','TW','JP','KR','SG','TH','VN','MY','MO']::text[], '{}', 'published', 80),
  ('octopus', 'Octopus', 'transport_local',
   'La carte qui paie tout à Hong Kong.',
   'Métro, bus, tram, ferry, mais aussi supérettes et distributeurs : c''est le moyen de paiement par défaut de la ville, et elle s''ajoute au téléphone.',
   null,
   'https://apps.apple.com/search?term=Octopus', 'https://play.google.com/store/search?q=Octopus&c=apps', 'https://www.octopus.com.hk',
   array['HK']::text[], '{}', 'published', 90),
  ('klook', 'Klook', 'activites',
   'Les billets et les pass de transport en Asie.',
   'Vend les entrées, mais surtout les cartes de transport, les cartes SIM et les navettes d''aéroport, souvent moins cher qu''au guichet et sans faire la queue à l''arrivée.',
   'Comparez avec GetYourGuide : les catalogues et les prix diffèrent sensiblement d''un pays à l''autre.',
   'https://apps.apple.com/search?term=Klook', 'https://play.google.com/store/search?q=Klook&c=apps', 'https://www.klook.com',
   array['HK','TW','JP','KR','SG','TH','MY','VN','PH','ID','CN','MO','IN']::text[], '{}', 'published', 75),
  ('safetravel', 'SafeTravel Iceland', 'securite',
   'L''état des routes et les alertes, en Islande.',
   'Une route peut fermer en quelques heures pour cause de vent ou de neige, y compris en été sur les pistes de l''intérieur. Le service officiel diffuse les alertes et permet de déposer son itinéraire aux secours.',
   null,
   'https://apps.apple.com/search?term=SafeTravel%20Iceland', 'https://play.google.com/store/search?q=SafeTravel%20Iceland&c=apps', 'https://safetravel.is',
   array['IS']::text[], '{}', 'published', 85),
  ('park4night', 'park4night', 'hebergement',
   'Où dormir en van, et où se garer la nuit.',
   'Des dizaines de milliers d''emplacements repérés par des voyageurs, avec la légalité, l''eau, les toilettes et le calme notés. Indispensable si le voyage se fait en van ou en voiture aménagée.',
   'Un emplacement toléré ne l''est pas partout ni toute l''année : les commentaires récents valent mieux que la fiche.',
   'https://apps.apple.com/search?term=park4night', 'https://play.google.com/store/search?q=park4night&c=apps', 'https://www.park4night.com',
   array['FR','ES','PT','IT','DE','AT','CH','BE','NL','HR','SI','GR','NO','SE','DK','IE','GB','PL','MA']::text[], '{}', 'published', 60),
  ('happycow', 'HappyCow', 'nourriture',
   'Manger végétarien, même là où c''est compliqué.',
   'Recense les adresses végétariennes et véganes dans le monde entier, y compris les petites cantines que les grandes applications d''avis ne référencent pas.',
   null,
   'https://apps.apple.com/search?term=HappyCow', 'https://play.google.com/store/search?q=HappyCow&c=apps', 'https://www.happycow.net',
   '{}', '{}', 'published', 50),
  ('alltrails', 'AllTrails', 'activites',
   'Les sentiers de randonnée, avec la trace hors ligne.',
   'Le tracé, le dénivelé et l''état du chemin décrits par ceux qui viennent de le faire. La trace téléchargée évite de dépendre du réseau une fois dans la montagne.',
   'Le téléchargement des cartes fait partie de l''offre payante : préparez la sortie avant si vous restez sur la version gratuite.',
   'https://apps.apple.com/search?term=AllTrails', 'https://play.google.com/store/search?q=AllTrails&c=apps', 'https://www.alltrails.com',
   '{}', '{}', 'published', 55),
  ('izi-travel', 'izi.TRAVEL', 'activites',
   'Des visites guidées audio, gratuites.',
   'Des milliers de parcours enregistrés par des musées et des offices de tourisme, à écouter en marchant. Se télécharge à l''avance et remplace un guide payant sur beaucoup de villes.',
   'La couverture et la qualité varient énormément d''une ville à l''autre : vérifiez avant de compter dessus.',
   'https://apps.apple.com/search?term=izi.TRAVEL', 'https://play.google.com/store/search?q=izi.TRAVEL&c=apps', 'https://izi.travel',
   '{}', '{}', 'published', 45),
  ('2gis', '2GIS', 'orientation',
   'La carte de référence en Asie centrale et dans le Caucase.',
   'Fonctionne entièrement hors ligne et connaît les commerces, les étages et les entrées d''immeuble que les cartes mondiales ignorent dans cette région.',
   null,
   'https://apps.apple.com/search?term=2GIS', 'https://play.google.com/store/search?q=2GIS&c=apps', 'https://2gis.com',
   array['KZ','UZ','KG','AZ','GE','AE','CY']::text[], '{}', 'published', 75)
on conflict (id) do update set
  name            = excluded.name,
  category        = excluded.category,
  tagline         = excluded.tagline,
  why             = excluded.why,
  caveat          = excluded.caveat,
  ios_url         = excluded.ios_url,
  android_url     = excluded.android_url,
  web_url         = excluded.web_url,
  country_codes   = excluded.country_codes,
  destination_ids = excluded.destination_ids,
  priority        = excluded.priority,
  -- On ne repasse pas en 'published' une fiche qu'un administrateur aurait
  -- retirée : la modération humaine prime sur la graine.
  status          = case when public.travel_apps.status = 'rejected'
                         then 'rejected' else excluded.status end,
  updated_at      = now();
